name = "CorrectMatch"
uuid = "26fcc630-e5d3-11e9-1f2e-33567d4860bc"
version = "1.3.1"
authors = ["Luc Rocher", "Julien Hendrickx", "Yves-Alexandre de Montjoye"]
description = "Statistical estimation of re-identification risks using Gaussian copula models"
repository = "https://github.com/computationalprivacy/CorrectMatch.jl"

[deps]
Discreet = "c2843242-4f35-58a6-a2a0-7e7527607317"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
PDMats = "90014a1f-27ba-587c-ab20-58faa44d9150"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
mvndst_jll = "78cd126e-648e-5a4b-8892-63be0e833cb1"

[compat]
Discreet = "1.0"
Distributions = "0.25"
LinearAlgebra = "1.9, 1.10, 1.11, 1.12, 1.13"
Optim = "1.9, 1.10, 1.11, 1.12, 1.13"
PDMats = "0.11"
Pkg = "1.9"
Random = "1.9"
Roots = "2.1, 2.2"
Statistics = "1.9"
StatsBase = "0.34"
StatsFuns = "1.3, 1.4, 1.5"
Test = "1.9"
julia = "1.9"
mvndst_jll = "1"
